Fixed bug in onMusicChanged in current playlist
On some platforms we get:
CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
So the onNotifyDaasetChanged is now called from the ui thread.