Upgrade to EventBus 2.4.1
This version fixes a NoClassDefFoundError, thus eliminates the need to
reference a special fork of EventBus, and thereby also removes an Android
Studio problem, as it seems the EventBus project does not work with
Android Studio/Intellij.